name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure latest changes are deployed
        run: |
          cd /home/azureuser/fastapi-book-project || exit 1  # Exit if directory doesn't exist
          git fetch --all
          git reset --hard origin/main
          git pull origin main
          sudo systemctl restart fastapi  # Restart FastAPI properly
          sudo systemctl restart nginx  # Ensures Nginx recognizes the new app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t chrisjrleon10/fastapi-app:latest .
          docker push chrisjrleon10/fastapi-app:latest

      - name: Deploy to Server (SSH)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 20.213.11.2
          username: azureuser
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/azureuser/fastapi-book-project || exit 1  # Ensure correct directory
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
            sudo systemctl restart nginx
            docker pull chrisjrleon10/fastapi-app:latest
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d -p 8080:8000 --name fastapi-app chrisjrleon10/fastapi-app:latest
            sleep 10  # Wait for the app to start
