name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t chrisjrleon10/fastapi-app:latest .
          docker push chrisjrleon10/fastapi-app:latest

      - name: Deploy to Server (SSH)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 20.213.11.2
          username: azureuser
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            sudo chown -R $USER:$USER /home/azureuser/fastapi-book-project/.git  # Change ownership
            sudo chmod -R u+w /home/azureuser/fastapi-book-project/.git         # Grant write permissions
            cd ~/fastapi-book-project
            sudo git fetch --all
            sudo git reset --hard origin/main  # Use sudo to override permission issues
            sudo git pull origin main
            source venv/bin/activate
            docker pull chrisjrleon10/fastapi-app:latest
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d -p 8080:8000 --name fastapi-app chrisjrleon10/fastapi-app:latest
            sleep 10  # Wait for the app to start
            sudo service nginx restart